set(MODULITH_PROJECT_NAME "Modulith")
set(MODULITH_PROJECT_VERSION 1.0.0)
set(MODULITH_PROJECT_DESCRIPTION "A modular game engine for component-driven development and modding")
set(MODULITH_PROJECT_LANGUAGES CXX C)

set(MODULITH_VCPKG_INCLUDE vcpkg_dir)

set(MODULITH_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/build)
set(MODULITH_MODDING_DIRECTORY ${MODULITH_OUTPUT_DIRECTORY}/modding)
set(MODULITH_MODULES_DIRECTORY ${MODULITH_OUTPUT_DIRECTORY}/modules)