# Copy Files
macro(MODULITH_COPY_FILE_TO_LOCATION TARGET INPUT OUTPUT LOCATION)
    add_custom_command(TARGET ${TARGET} POST_BUILD
            COMMAND ${CMAKE_COMMAND} -E copy_if_different ${INPUT} ${LOCATION}/${OUTPUT}
    )
endmacro(MODULITH_COPY_FILE_TO_LOCATION TARGET INPUT OUTPUT LOCATION)

macro(MODULITH_COPY_FILE_TO_OUTPUT TARGET INPUT OUTPUT)
    MODULITH_COPY_FILE_TO_LOCATION(${TARGET} ${INPUT} ${OUTPUT} ${MODULITH_OUTPUT_DIRECTORY})
endmacro(MODULITH_COPY_FILE_TO_OUTPUT TARGET INPUT OUTPUT)

macro(MODULITH_COPY_FILE_TO_MODDING TARGET INPUT OUTPUT)
    MODULITH_COPY_FILE_TO_LOCATION(${TARGET} ${INPUT} ${OUTPUT} ${MODULITH_MODDING_DIRECTORY})
endmacro(MODULITH_COPY_FILE_TO_MODDING TARGET INPUT OUTPUT)

macro(MODULITH_COPY_DIR_TO_LOCATION TARGET INPUT OUTPUT LOCATION)
    add_custom_command(TARGET ${TARGET} POST_BUILD
            COMMAND ${CMAKE_COMMAND} -E copy_directory ${INPUT} ${LOCATION}/${OUTPUT}
    )
endmacro(MODULITH_COPY_DIR_TO_LOCATION TARGET INPUT OUTPUT LOCATION)

macro(MODULITH_COPY_DIR_TO_OUTPUT TARGET INPUT OUTPUT)
    MODULITH_COPY_DIR_TO_LOCATION(${TARGET} ${INPUT} ${OUTPUT} ${MODULITH_OUTPUT_DIRECTORY})
endmacro(MODULITH_COPY_DIR_TO_OUTPUT TARGET INPUT OUTPUT)

macro(MODULITH_COPY_DIR_TO_MODDING TARGET INPUT OUTPUT)
    MODULITH_COPY_DIR_TO_LOCATION(${TARGET} ${INPUT} ${OUTPUT} ${MODULITH_MODDING_DIRECTORY})
endmacro(MODULITH_COPY_DIR_TO_MODDING TARGET INPUT OUTPUT)